name: Setup with Bun
description: Perform standard setup and install dependencies using bun.
inputs:
  node-version:
    description: The version of Node.js to install
    required: true
    default: 22.x

runs:
  using: composite
  steps:
    - name: Install unzip (for containers)
      shell: bash
      run: command -v unzip &> /dev/null || (apt-get update && apt-get install -y unzip)

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2

    - name: Set Node.js (${{ inputs.node-version }})
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile --silent